name: Deploy Site 2 to InfinityFree via FTP

on:
push:
branches:
- site2

jobs:
ftp-deploy:
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@v3

  - name: FTP Deploy
    uses: SamKirkland/FTP-Deploy-Action@4.3.0
    with:
      server: ftpupload.net
      username: ${{ secrets.FTP_USERNAME2 }}
      password: ${{ secrets.FTP_PASSWORD2 }}
      local-dir: ./
      server-dir: /test-project2.free.nf/htdocs/
